/**
 * This file contains all translations for the video guide: https://dota-coach.com/video/DotaCoachTutorial.mp4
 *
 * Tutorial is translated into the following languages:
 *   - English
 *   - German
 *   - French
 *   - Russian
 *   - Chinese
 *   - Brazilian Portugese
 *   - Spanish
 *
 * Comment: Amazon Polly doesn't support the following languages:
 *   - Indonesian
 *   - Filipino
 *
 */

import { Translations } from "./i18n";

export const VideoGuideTranslations: Translations = {
  "00_Introduction": {
    en: "Welcome to Dota Coach and thank you for your interest! You will be able to step up your Dota game play immediately after watching this short guide!",
    de: "Willkommen bei Dota Coach und vielen Dank für Ihr Interesse! Sie können Ihr Dota-Spiel sofort nach dem Anschauen dieser Kurzanleitung verbessern!", // #toBeUpdated
    fr: "Bienvenue chez Dota Coach et merci de votre intérêt ! Vous pourrez améliorer votre jeu Dota immédiatement après avoir regardé ce petit guide !", // #toBeUpdated
    ru: "Добро пожаловать в Dota Coach и благодарим вас за проявленный интерес! Вы сможете улучшить свою игру в Dota сразу после просмотра этого краткого руководства!", // #toBeUpdated
    //id: "Selamat datang di Dota Coach dan terima kasih atas minat Anda! Anda akan dapat meningkatkan permainan Dota Anda segera setelah menonton panduan singkat ini!", // #toBeUpdated
    //fil: "Maligayang pagdating sa Dota Coach at salamat sa iyo para sa iyong interes! Magagawa mong upang hakbang up ang iyong Dota laro play kaagad pagkatapos nanonood ng maikling gabay na ito!", // #toBeUpdated
    zh: "欢迎来到Dota Coach，感谢您的关注！看完这篇简短的指南后，你将能够立即提高你的Dota游戏玩法！", // #toBeUpdated
    br: "Bem-vindo ao Dota Coach e obrigado pelo seu interesse! Você será capaz de intensificar seu jogo Dota imediatamente após assistir a este pequeno guia!", // #toBeUpdated
    es: "¡Bienvenido a Dota Coach y gracias por tu interés! ¡Podrás mejorar tu juego de Dota inmediatamente después de ver esta breve guía!", // #toBeUpdated
  },
  "01_GameStateIntegration": {
    en: "Before you use the app, make sure to add the game state integration parameter to your Dota 2 launch options. Without it, Dota Coach won't work!",
    de: "Stellen Sie vor der Verwendung der App sicher, dass Sie den Integrationsparameter für den Spielstatus zu Ihren Dota 2-Startoptionen hinzufügen. Ohne sie funktioniert Dota Coach nicht!", // #toBeUpdated
    fr: "Avant d'utiliser l'application, assurez-vous d'ajouter le paramètre d'intégration de l'état du jeu à vos options de lancement Dota 2. Sans cela, Dota Coach ne fonctionnera pas !", // #toBeUpdated
    ru: "Перед использованием приложения обязательно добавьте параметр интеграции состояния игры в параметры запуска Dota 2. Без него тренер по Dota не будет работать!", // #toBeUpdated
    //id: "Sebelum Anda menggunakan aplikasi, pastikan untuk menambahkan parameter integrasi status permainan ke opsi peluncuran Dota 2 Anda. Tanpa itu, Pelatih Dota tidak akan bekerja!", // #toBeUpdated
    //fil: "Bago mo gamitin ang app, siguraduhing idagdag ang parameter ng pagsasama ng estado ng laro sa iyong mga pagpipilian sa paglunsad ng Dota 2. Kung wala ito, ang Dota Coach ay hindi gagana!", // #toBeUpdated
    zh: "在使用应用程序之前，请务必将游戏状态集成参数添加到Dota 2启动选项中。没有它，Dota Coach 将无法正常工作！", // #toBeUpdated
    br: "Antes de usar o aplicativo, certifique-se de adicionar o parâmetro de integração do estado do jogo às suas opções de inicialização do Dota 2. Sem isso, o Dota Coach não funcionará!", // #toBeUpdated
    es: "Antes de usar la aplicación, asegúrate de añadir el parámetro de integración del estado del juego a tus opciones de lanzamiento de Dota 2. ¡Sin él, Dota Coach no funcionará!", // #toBeUpdated
  },
  "02_DesktopWindow": {
    en: "You can move the apps desktop window by left click dragging the window to your desired position. To always be informed what new features have been patched in, check the initial notification panel. If you are a first-time app user, check out the written guide in the notification window as well! If Dota or steam services are unavailable, the status will change accordingly. If the app is not working, please check out the app status in the top left corner! A green circle means all is good, if it turns amber, some Dota services might be down.",
    de: "Sie können das Desktop-Fenster der App verschieben, indem Sie das Fenster mit der linken Maustaste an die gewünschte Position ziehen. Um immer informiert zu sein, welche neuen Funktionen gepatcht wurden, überprüfen Sie das anfängliche Benachrichtigungsfeld. Wenn Sie ein erstmaliger App-Benutzer sind, lesen Sie auch den schriftlichen Leitfaden im Benachrichtigungsfenster! Wenn Dota- oder Steam-Dienste nicht verfügbar sind, ändert sich der Status entsprechend. Wenn die App nicht funktioniert, überprüfe bitte den App-Status in der oberen linken Ecke! Ein grüner Kreis bedeutet, dass alles in Ordnung ist. Wenn es gelb wird, sind einige Dota-Dienste möglicherweise nicht verfügbar.", // #toBeUpdated
    fr: "Vous pouvez déplacer la fenêtre du bureau des applications en cliquant avec le bouton gauche de la souris en faisant glisser la fenêtre vers la position souhaitée. Pour être toujours informé des nouvelles fonctionnalités qui ont été corrigées, consultez le panneau de notification initial. Si vous utilisez une application pour la première fois, consultez également le guide écrit dans la fenêtre de notification ! Si les services Dota ou Steam ne sont pas disponibles, le statut changera en conséquence. Si l'application ne fonctionne pas, veuillez consulter l'état de l'application dans le coin supérieur gauche ! Un cercle vert signifie que tout va bien, s'il devient orange, certains services Dota peuvent être en panne.", // #toBeUpdated
    ru: "Окно рабочего стола приложения можно переместить, щелкнув левой кнопкой мыши, перетащив окно в нужное место. Чтобы всегда быть в курсе, какие новые функции были исправлены, проверяйте начальную панель уведомлений. Если вы впервые пользуетесь приложением, ознакомьтесь с письменным руководством в окне уведомлений! Если сервисы Dota или steam будут недоступны, статус изменится соответствующим образом. Если приложение не работает, проверьте статус приложения в левом верхнем углу! Зеленый круг означает, что все хорошо, если он станет янтарным, некоторые сервисы Dota могут быть недоступны.", // #toBeUpdated
    //id: "Anda dapat memindahkan jendela desktop aplikasi dengan klik kiri menyeret jendela ke posisi yang Anda inginkan. Untuk selalu mengetahui fitur baru apa yang telah ditambal, periksa panel notifikasi awal. Jika Anda adalah pengguna aplikasi pertama kali, periksa panduan tertulis di jendela notifikasi juga! Jika layanan Dota atau uap tidak tersedia, statusnya akan berubah sesuai. Jika aplikasi tidak berfungsi, silakan periksa status aplikasi di sudut kiri atas! Lingkaran hijau berarti semuanya baik, jika ternyata kuning, beberapa layanan Dota mungkin turun.", // #toBeUpdated
    //fil: "Maaari mong ilipat ang desktop window ng apps sa pamamagitan ng kaliwang pag-click sa pag-drag sa window sa iyong ninanais na posisyon. Upang palaging malaman kung anong mga bagong tampok ang na-patched in, suriin ang paunang panel ng abiso. Kung ikaw ay isang unang beses na gumagamit ng app, tingnan ang nakasulat na gabay sa window ng abiso pati na rin! Kung ang mga serbisyo ng Dota o steam ay hindi magagamit, ang katayuan ay magbabago nang naaayon. Kung hindi gumagana ang app, mangyaring tingnan ang katayuan ng app sa kaliwang sulok sa itaas! Ang isang berdeng bilog ay nangangahulugan na ang lahat ay mabuti, kung ito ay lumiliko amber, ang ilang mga serbisyo ng Dota ay maaaring pababa.", // #toBeUpdated
    zh: "您可以通过左键单击将窗口拖动到所需位置来移动应用程序的桌面窗口。要随时了解已修补了哪些新功能，请查看初始通知面板。如果您是首次使用应用程序，请在通知窗口中查看书面指南！如果 Dota 或 Steam 服务不可用，状态将相应改变。如果应用程序无法正常工作，请在左上角查看应用程序状态！绿色圆圈表示一切都很好，如果它变成琥珀色，某些Dota服务可能会关闭。", // #toBeUpdated
    br: "Você pode mover a janela da área de trabalho do aplicativo clicando com o botão esquerdo arrastando a janela para a posição desejada. Para estar sempre informado sobre quais novos recursos foram corrigidos, verifique o painel de notificação inicial. Se você é um usuário de aplicativo pela primeira vez, confira o guia escrito na janela de notificação também! Se os serviços Dota ou Steam não estiverem disponíveis, o status mudará de acordo. Se o aplicativo não estiver funcionando, verifique o status do aplicativo no canto superior esquerdo! Um círculo verde significa que tudo está bem, se ficar âmbar, alguns serviços do Dota podem estar fora do ar.", // #toBeUpdated
    es: "Puede mover la ventana del escritorio de la aplicación haciendo clic con el botón izquierdo y arrastrando la ventana a la posición deseada. Para estar siempre informado de las nuevas funciones que se han aplicado parches, consulte el panel de notificaciones inicial. Si es la primera vez que usa una aplicación, consulte también la guía escrita en la ventana de notificación. Si los servicios de Dota o Steam no están disponibles, el estado cambiará en consecuencia. Si la aplicación no funciona, consulte el estado de la aplicación en la esquina superior izquierda. Un círculo verde significa que todo está bien, si se vuelve ámbar, algunos servicios de Dota podrían estar inactivos.", // #toBeUpdated
  },
  "03_SettingsWindow": {
    en: "The settings window can be found in the top right corner after clicking on the menu icon. You can customize every single component of the app by disabling or enabling it and you are able to freely position all windows that are shown in game. Click the reposition button in the bottom right corner of the settings window. Once all windows turn green, left click drag them. Do not forget to turn off the reposition once you are done.",
    de: "Das Einstellungsfenster befindet sich in der oberen rechten Ecke, nachdem Sie auf das Menüsymbol geklickt haben. Sie können jede einzelne Komponente der App anpassen, indem Sie sie deaktivieren oder aktivieren, und Sie können alle Fenster, die im Spiel angezeigt werden, frei positionieren. Klicken Sie in der unteren rechten Ecke des Einstellungsfensters auf die Schaltfläche „Neupositionierung“. Sobald alle Fenster grün werden, ziehen Sie sie mit der linken Maustaste. Vergessen Sie nicht, die Neupositionierung auszuschalten, sobald Sie fertig sind.", // #toBeUpdated
    fr: "La fenêtre des paramètres se trouve dans le coin supérieur droit après avoir cliqué sur l'icône du menu. Vous pouvez personnaliser chaque composant de l'application en le désactivant ou en l'activant et vous pouvez positionner librement toutes les fenêtres affichées dans le jeu. Cliquez sur le bouton de repositionnement dans le coin inférieur droit de la fenêtre des paramètres. Une fois que toutes les fenêtres deviennent vertes, faites glisser un clic gauche. N'oubliez pas de désactiver le repositionnement une fois que vous avez terminé.", // #toBeUpdated
    ru: "Окно настроек можно найти в правом верхнем углу после нажатия на значок меню. Вы можете настроить каждый компонент приложения, отключив или включив его, и вы сможете свободно размещать все окна, отображаемые в игре. Нажмите кнопку перемещения в правом нижнем углу окна настроек. Когда все окна станут зелеными, щелкните левой кнопкой мыши и перетащите их. Не забудьте отключить репозицию, как только закончите.", // #toBeUpdated
    //id: "Jendela pengaturan dapat ditemukan di sudut kanan atas setelah mengklik ikon menu. Anda dapat menyesuaikan setiap komponen aplikasi dengan menonaktifkan atau mengaktifkannya dan Anda dapat dengan bebas memposisikan semua jendela yang ditampilkan dalam game. Klik tombol reposisi di sudut kanan bawah jendela pengaturan. Setelah semua jendela menjadi hijau, klik kiri seret mereka. Jangan lupa untuk mematikan reposisi setelah Anda selesai.", // #toBeUpdated
    //fil: "Ang window ng mga setting ay matatagpuan sa kanang sulok sa itaas pagkatapos ng pag-click sa icon ng menu. Maaari mong i-customize ang bawat solong bahagi ng app sa pamamagitan ng hindi pagpapagana o pagpapagana nito at maaari mong malayang iposisyon ang lahat ng mga bintana na ipinapakita sa laro. I-click ang pindutan ng muling posisyon sa kanang sulok sa ibaba ng window ng mga setting. Kapag ang lahat ng mga bintana ay nagiging berde, kaliwa-click i-drag ang mga ito. Huwag kalimutang i-off ang muling posisyon sa sandaling tapos ka na.", // #toBeUpdated
    zh: "单击菜单图标后，可以在右上角找到设置窗口。您可以通过禁用或启用应用程序来自定义应用程序的每个组件，并且可以自由放置游戏中显示的所有窗口。单击设置窗口右下角的重新定位按钮。所有窗口变为绿色后，左键单击拖动它们。完成后，不要忘记关闭重新定位。", // #toBeUpdated
    br: "A janela de configurações pode ser encontrada no canto superior direito depois de clicar no ícone do menu. Você pode personalizar cada componente do aplicativo desativando-o ou ativando-o e pode posicionar livremente todas as janelas que são mostradas no jogo. Clique no botão de reposição no canto inferior direito da janela de configurações. Quando todas as janelas ficarem verdes, clique com o botão esquerdo e arraste-as. Não se esqueça de desligar a reposição quando terminar.", // #toBeUpdated
    es: "La ventana de configuración se encuentra en la esquina superior derecha después de hacer clic en el icono del menú. Puede personalizar cada componente de la aplicación deshabilitándolo o habilitándolo y puede colocar libremente todas las ventanas que se muestran en el juego. Haga clic en el botón de cambio de posición en la esquina inferior derecha de la ventana de configuración. Cuando todas las ventanas se pongan verdes, haz clic izquierdo y arrástralas. No olvide desactivar la reposición una vez que haya terminado.", // #toBeUpdated
  },
  "04_InGameWindow": {
    en: "The in-game window can be opened and closed by clicking on the Dota Coach logo which can be found at the top left corner during the draft and above the mini-map during the game. There are two different windows inside the in-game window. The pick, ban and player information, as well as the coaching information that lets you select the role you are playing, as well as your lane enemies. You will also get counter item suggestions for the early-game. Another feature we provide are in-game guides directly on steam. You can immediately get them by clicking on “get steam guide”. Do not forget to restart Dota after you selected one you like!",
    de: "Das Fenster im Spiel kann geöffnet und geschlossen werden, indem Sie auf das Dota Coach-Logo klicken, das sich während des Drafts in der oberen linken Ecke und während des Spiels über der Minikarte befindet. Im Spielfenster gibt es zwei verschiedene Fenster. Die Auswahl-, Ban- und Spielerinformationen sowie die Coaching-Informationen, mit denen Sie die Rolle, die Sie spielen, sowie Ihre Lane-Feinde auswählen können. Sie erhalten auch Vorschläge für Gegengegenstände für das frühe Spiel. Ein weiteres Feature, das wir anbieten, sind Guides im Spiel direkt auf Steam Sie können sie sofort erhalten, indem Sie auf „Steam Guide holen“ klicken. Vergessen Sie nicht, Dota neu zu starten, nachdem Sie eine ausgewählt haben, die Ihnen gefällt!", // #toBeUpdated
    fr: "La fenêtre du jeu peut être ouverte et fermée en cliquant sur le logo Dota Coach qui se trouve en haut à gauche pendant le draft et au-dessus de la mini-carte pendant le jeu. Il y a deux fenêtres différentes à l'intérieur de la fenêtre du jeu. Les informations sur le choix, le bannissement et le joueur, ainsi que les informations d'entraînement qui vous permettent de sélectionner le rôle que vous jouez, ainsi que vos ennemis de voie. Vous recevrez également des suggestions d'objets de comptoir pour le début de partie. Les guides en jeu directement sur Steam sont une autre fonctionnalité que nous proposons. Vous pouvez les obtenir immédiatement en cliquant sur « Obtenir le guide Steam ». N'oubliez pas de redémarrer Dota après avoir sélectionné celui que vous aimez !", // #toBeUpdated
    ru: "Внутриигровое окно можно открыть и закрыть, нажав на логотип Dota Coach, который находится в левом верхнем углу во время драфта и над мини-картой во время игры. Во внутриигровом окне есть два разных окна. Информация о выборе, бане и игроке, а также информация о коучинге, которая позволяет вам выбрать роль, которую вы играете, а также врагов на линии. Вы также получите предложения по контратакам на ранней стадии игры. Еще одна функция, которую мы предоставляем, — это внутриигровые руководства прямо в steam. Вы можете сразу получить их, нажав на кнопку «получить steam guide». Не забудьте перезапустить Dota после того, как вы выбрали тот, который вам нравится!", // #toBeUpdated
    //id: "Jendela dalam game dapat dibuka dan ditutup dengan mengklik logo Dota Coach yang dapat ditemukan di pojok kiri atas selama draft dan di atas peta mini selama pertandingan berlangsung. Ada dua jendela yang berbeda di dalam jendela dalam game. Memilih, melarang dan informasi pemain, serta informasi pembinaan yang memungkinkan Anda memilih peran Anda bermain, serta musuh jalur Anda. Anda juga akan mendapatkan saran item kontra untuk game awal. Fitur lain yang kami sediakan adalah panduan dalam game langsung pada uap. Anda dapat segera mendapatkan mereka dengan mengklik 'mendapatkan panduan uap'. Jangan lupa untuk me-restart Dota setelah Anda memilih salah satu yang Anda suka!", // #toBeUpdated
    //fil: "Ang in-game window ay mabubuksan at isara sa pamamagitan ng pag-click sa logo ng Dota Coach na matatagpuan sa itaas na kaliwang sulok sa panahon ng draft at sa itaas ng mini-mapa sa panahon ng laro. Mayroong dalawang magkakaibang bintana sa loob ng in-game window. Ang pick, ban at impormasyon ng manlalaro, pati na rin ang impormasyon sa pagtuturo na nagpapahintulot sa iyo na piliin ang papel na iyong nilalaro, pati na rin ang iyong mga kaaway sa lane. Makakakuha ka rin ng mga suhestiyon ng counter item para sa maagang laro. Ang isa pang tampok na aming ibinibigay ay mga gabay sa in-game nang direkta sa steam. Maaari mong agad na makuha ang mga ito sa pamamagitan ng pag-click sa 'makakuha ng steam guide'. Huwag kalimutang i-restart ang Dota pagkatapos mong piliin ang isa na gusto mo!", // #toBeUpdated
    zh: "可以通过单击Dota Coach徽标来打开和关闭游戏中的窗口，该徽标位于草稿期间的左上角，在游戏期间位于小地图上方.游戏窗口内有两个不同的窗口。选择、禁令和球员信息，以及教练信息，让你选择自己扮演的角色以及你的车道敌人。你还将获得游戏初期的反击物品建议。我们提供的另一个功能是直接在Steam上播放的游戏内指南。你可以通过点 击 “获取蒸汽指南” 立即获取它们。选择你喜欢的Dota后，别忘了重启Dota！", // #toBeUpdated
    br: "A janela do jogo pode ser aberta e fechada clicando no logotipo do Dota Coach, que pode ser encontrado no canto superior esquerdo durante o rascunho e acima do minimapa durante o jogo. Existem duas janelas diferentes dentro da janela do jogo. As informações de escolha, banimento e jogador, bem como as informações de treinamento que permitem selecionar o papel que você está desempenhando, bem como seus inimigos de pista. Você também receberá sugestões de itens de contador para o início do jogo. Outro recurso que oferecemos são os guias do jogo diretamente no Steam. Você pode obtê-los imediatamente clicando em 'obter guia do vapor'. Não se esqueça de reiniciar o Dota depois de selecionar um que você gosta!", // #toBeUpdated
    es: "La ventana del juego se puede abrir y cerrar haciendo clic en el logotipo de Dota Coach, que se encuentra en la esquina superior izquierda durante el draft y encima del minimapa durante el juego. Hay dos ventanas diferentes dentro de la ventana del juego. La información de selección, expulsión y jugador, así como la información de entrenamiento que te permite seleccionar el rol que estás jugando, así como los enemigos de tu carril. También recibirás sugerencias de artículos para contrarrestar al principio de la partida. Otra característica que ofrecemos son las guías del juego directamente en Steam. Puede obtenerlos de inmediato haciendo clic en «obtener guía de vapor». ¡No olvides reiniciar Dota después de seleccionar uno que te guste!", // #toBeUpdated
  },
  "05_Timers": {
    en: "The app provides timers for all important game events: Buybacks, roshan, glyph, ultimates and runes. You can disable and enable them in the settings menu. Left clicking them will start the timer: left clicking on a running timer will announce the timer in the team chat. Clicking the red x next to the timer will reset it. These features work for all timers that can be started by clicking them.",
    de: "Die App bietet Timer für alle wichtigen Spielereignisse: Rückkäufe, Roshan, Glyphe, Ultimaten und Runen. Sie können sie im Einstellungsmenü deaktivieren und aktivieren. Wenn Sie mit der linken Maustaste darauf klicken, wird der Timer gestartet: Ein Linksklick auf einen laufenden Timer kündigt den Timer im Teamchat an. Wenn Sie auf das rote x neben dem Timer klicken, wird es zurückgesetzt. Diese Funktionen funktionieren für alle Timer, die durch Anklicken gestartet werden können.", // #toBeUpdated
    fr: "L'application fournit des minuteries pour tous les événements de jeu importants : rachats, roshan, glyphes, ultimes et runes. Vous pouvez les désactiver et les activer dans le menu des paramètres. Un clic gauche lancera le chronomètre : un clic gauche sur un chronomètre en cours d'exécution annoncera le chronomètre dans le chat d'équipe. Cliquez sur le x rouge à côté du minuteur pour le réinitialiser. Ces fonctionnalités fonctionnent pour tous les minuteurs qui peuvent être démarrés en cliquant dessus.", // #toBeUpdated
    ru: "Приложение предоставляет таймеры для всех важных игровых событий: выкупа, рошана, глифа, ультиматов и рун. Их можно отключить и включить в меню настроек. Щелчок левой кнопкой мыши запускает таймер: щелчок левой кнопкой мыши по таймеру запустит таймер в командном чате. Нажатие красного x рядом с таймером приведет к его сбросу. Эти функции работают для всех таймеров, которые можно запустить, щелкнув по ним.", // #toBeUpdated
    //id: "Aplikasi ini menyediakan timer untuk semua acara game penting: Buybacks, roshan, mesin terbang, ultimates dan rune. Anda dapat menonaktifkan dan mengaktifkannya di menu pengaturan. Kiri mengklik mereka akan memulai timer: mengklik kiri pada timer berjalan akan mengumumkan timer dalam obrolan tim. Mengklik x merah di sebelah timer akan meresetnya. Fitur-fitur ini bekerja untuk semua timer yang dapat dimulai dengan mengkliknya.", // #toBeUpdated
    //fil: "Ang app ay nagbibigay ng timers para sa lahat ng mahahalagang kaganapan sa laro: Buybacks, roshan, glyph, ultimates at runes. Maaari mong hindi paganahin at paganahin ang mga ito sa menu ng mga setting. Ang kaliwang pag-click sa kanila ay magsisimula ng timer: ang kaliwang pag-click sa isang tumatakbo na timer ay ipahayag ang timer sa chat ng koponan. Ang pag-click sa pulang x sa tabi ng timer ay i-reset ito. Ang mga tampok na ito ay gumagana para sa lahat ng mga timers na maaaring magsimula sa pamamagitan ng pag-click sa mga ito.", // #toBeUpdated
    zh: "该应用程序提供所有重要游戏事件的计时器：回购、roshan、glyph、Ultimates 和符文。您可以在设置菜单中禁用和启用它们。左键单击它们将启动计时器：左键单击正在运行的计时器将在团队聊天中宣布计时器。单击计时器旁边的红色 x 将重置计时器。这些功能适用于所有可以通过单击它们启动的计时器。", // #toBeUpdated
    br: "O aplicativo fornece temporizadores para todos os eventos importantes do jogo: recompra, roshan, glifo, ultimatos e runas. Você pode desativá-los e ativá-los no menu de configurações. Clicar com o botão esquerdo neles iniciará o cronômetro: clicar com o botão esquerdo em um cronômetro em execução anunciará o cronômetro no bate-papo da equipe. Clicar no x vermelho ao lado do cronômetro o redefinirá. Esses recursos funcionam para todos os temporizadores que podem ser iniciados clicando neles.", // #toBeUpdated
    es: "La aplicación proporciona temporizadores para todos los eventos importantes del juego: recompras, roshan, glifo, ultimates y runas. Puede desactivarlos y habilitarlos en el menú de configuración. Al hacer clic con el botón izquierdo, se iniciará el temporizador: al hacer clic izquierdo en un temporizador en ejecución, se anunciará el temporizador en el chat del equipo. Al hacer clic en la x roja junto al temporizador, se restablecerá. Estas funciones funcionan para todos los temporizadores que se pueden iniciar haciendo clic en ellos.", // #toBeUpdated
  },
  "06_Infoboxes": {
    en: "Player infoboxes provide information about the players and hero they are playing. You can disable or enable them in the settings menu. It will show standard item builds and timings, as well as provide valuable player information if available. You can check if their profile is private or public, and get a warning if we believe the player is a smurf. The team infobox can be found at the top middle which provides compiled information about the enemy team like disables.",
    de: "Spieler-Infoboxen liefern Informationen über die Spieler und Helden, die sie spielen. Sie können sie im Einstellungsmenü deaktivieren oder aktivieren. Es zeigt Standard-Item-Builds und Timings an und liefert wertvolle Spielerinformationen, falls verfügbar. Du kannst überprüfen, ob ihr Profil privat oder öffentlich ist, und eine Warnung erhalten, wenn wir glauben, dass der Spieler ein Schlumpf ist. Die Team-Infobox befindet sich in der oberen Mitte und bietet zusammengestellte Informationen über das gegnerische Team wie Behinderte.", // #toBeUpdated
    fr: "Les infoboxes des joueurs fournissent des informations sur les joueurs et les héros auxquels ils jouent. Vous pouvez les désactiver ou les activer dans le menu des paramètres. Il affichera les builds et les horaires des objets standard, ainsi que des informations précieuses sur le joueur, le cas échéant. Vous pouvez vérifier si leur profil est privé ou public, et recevoir un avertissement si nous pensons que le joueur est un schtroumpf. La boîte d'information de l'équipe se trouve en haut au milieu et fournit des informations compilées sur l'équipe ennemie, comme les désactivations.", // #toBeUpdated
    ru: "Инфобоксы игроков содержат информацию об игроках и героях, за которых они играют. Их можно отключить или включить в меню настроек. Он покажет стандартные сборки предметов и тайминги, а также предоставит ценную информацию об игроках, если таковая имеется. Вы можете проверить, является ли их профиль закрытым или общедоступным, и получить предупреждение, если мы считаем, что игрок смурф. Информационное окно команды находится вверху посередине, где собрана информация о вражеской команде, например об инвалидах.", // #toBeUpdated
    //id: "Infobox pemain memberikan informasi tentang pemain dan pahlawan yang mereka mainkan. Anda dapat menonaktifkan atau mengaktifkannya di menu pengaturan. Ini akan menunjukkan item standar membangun dan timing, serta memberikan informasi pemain yang berharga jika tersedia. Anda dapat memeriksa apakah profil mereka bersifat pribadi atau publik, dan mendapatkan peringatan jika kami yakin pemain adalah smurf. Infobox tim dapat ditemukan di tengah atas yang menyediakan informasi yang dikompilasi tentang tim musuh seperti menonaktifkan.", // #toBeUpdated
    //fil: "Ang mga infobox ng manlalaro ay nagbibigay ng impormasyon tungkol sa mga manlalaro at bayani na nilalaro nila. Maaari mong hindi paganahin o paganahin ang mga ito sa menu ng mga setting. Ipapakita nito ang karaniwang mga build ng item at timing, pati na rin magbigay ng mahalagang impormasyon ng manlalaro kung magagamit. Maaari mong suriin kung pribado o pampubliko ang kanilang profile, at makakuha ng babala kung naniniwala kami na ang manlalaro ay isang smurf. Ang infobox ng koponan ay matatagpuan sa tuktok na gitna, na nagbibigay ng naipon na impormasyon tungkol sa koponan ng kaaway tulad ng mga hindi pinapagana.", // #toBeUpdated
    zh: "玩家信息框提供有关他们正在玩的玩家和英雄的信息。您可以在设置菜单中禁用或启用它们。它将显示标准物品的构建和时间，并提供有价值的玩家信息（如果有）。您可以检查他们的个人资料是私人还是公开的，如果我们认为该玩家是蓝精灵，则会收到警告。队伍信息框位于顶部的中间，它提供了有关敌方队伍的汇编信息，例如禁用。", // #toBeUpdated
    br: "As caixas de informações do jogador fornecem informações sobre os jogadores e heróis que estão jogando. Você pode desativá-los ou ativá-los no menu de configurações. Ele mostrará compilações e tempos de itens padrão, bem como fornecerá informações valiosas ao jogador, se disponíveis. Você pode verificar se o perfil deles é privado ou público, e receber um aviso se acreditarmos que o jogador é um smurf. A caixa de informações da equipe pode ser encontrada no meio superior, que fornece informações compiladas sobre a equipe inimiga, como desabilita.", // #toBeUpdated
    es: "Los cuadros de información del jugador proporcionan información sobre los jugadores y el héroe con los que están jugando. Puede desactivarlos o habilitarlos en el menú de configuración. Mostrará construcciones y tiempos de objetos estándar, además de proporcionar información valiosa al jugador si está disponible. Puedes comprobar si su perfil es privado o público, y recibir una advertencia si creemos que el jugador es un pitufo. El cuadro de información del equipo se puede encontrar en la parte superior central, que proporciona información recopilada sobre el equipo enemigo, como las deshabilitaciones.", // #toBeUpdated
  },
};
